### ISSUE TITLE
PHP Notice: Undefined offset

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/remove-footer-credit#9]
Since updating to version 1.0.6, my wp-debug.log file is flooded with the following error:
PHP Notice: Undefined offset: 1 in /wp-content/plugins/remove-footer-credit/remove-footer-credit.php on line 214

https://wordpress.org/support/topic/php-notice-undefined-offset-12/

**Comment by mplusb** [comment]
solved in 1.0.10
